services:
  postgres:
    image: postgres:16-alpine
    container_name: gym_postgres
    restart: always
    environment:
      POSTGRES_DB: multi_gym_db
      POSTGRES_USER: multi_gym_user
      POSTGRES_PASSWORD: multi_gym_password
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
