// src/pages/mitra/MitraDashboard.tsx
import React, { useState, useCallback } from "react";
import { ScanLine, Clock, CheckCircle, XCircle } from "lucide-react";
import PinInput from "../../components/forms/PinInput";
import Button from "../../components/ui/Button";
import {
  useGetTransactions,
  useValidatePin,
} from "../../hooks/api/useMitraAPI";

/**
 * Mitra dashboard: PIN validation and recent entries from live backend.
 * useGetTransactions pulls the Mitra's own transactions via GET /api/transactions
 * (scoped by auth:sanctum to the logged-in mitra).
 */
const MitraDashboard: React.FC = () => {
  const [pin, setPin] = useState("");
  const [pinError, setPinError] = useState("");

  // Live data — backend scopes this to the mitra's own gyms automatically
  const { data: entries = [], isLoading: entriesLoading } =
    useGetTransactions();
  const validatePin = useValidatePin();

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      setPinError("");
      const trimmedPin = pin.replace(/\s/g, "");
      if (trimmedPin.length !== 4 || !/^\d{4}$/.test(trimmedPin)) {
        setPinError("PIN must be exactly 4 digits");
        return;
      }
      validatePin.mutate(
        { pin_code: trimmedPin },
        {
          onSuccess: () => {
            setPin("");
            setPinError("");
          },
          onError: (error: import('axios').AxiosError<{ message?: string }>) => {
            setPinError(
              error.response?.data?.message ||
                "Invalid or expired PIN",
            );
          },
        },
      );
    },
    [pin, validatePin],
  );

  const formatTime = (iso: string): string =>
    new Date(iso).toLocaleTimeString("id-ID", {
      hour: "2-digit",
      minute: "2-digit",
    });

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 md:p-10">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-xl bg-yellow-500/10 mb-4">
            <ScanLine size={28} className="text-yellow-500" />
          </div>
          <h1 className="text-2xl md:text-3xl font-bold text-white">
            Validate Member Access
          </h1>
          <p className="text-zinc-400 mt-2">
            Enter the 4-digit PIN generated by the member's app
          </p>
        </div>
        <form
          onSubmit={handleSubmit}
          className="flex flex-col items-center gap-6"
        >
          <PinInput
            value={pin}
            onChange={setPin}
            disabled={validatePin.isPending}
            error={pinError}
          />
          <Button
            type="submit"
            variant="primary"
            isLoading={validatePin.isPending}
            className="w-full max-w-xs py-4 text-lg font-extrabold tracking-wide"
          >
            {validatePin.isPending ? "Validating..." : "VALIDATE PIN"}
          </Button>
        </form>
      </div>

      <div>
        <div className="flex items-center gap-2 mb-4">
          <Clock size={18} className="text-zinc-400" />
          <h2 className="text-lg font-semibold text-white">Recent Entries</h2>
        </div>
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-zinc-800 text-zinc-400 uppercase text-xs tracking-wider text-center">
                  <th className="px-6 py-4 font-medium">Status</th>
                  <th className="px-6 py-4 font-medium">Member Name</th>
                  <th className="px-6 py-4 font-medium">Credit</th>
                  <th className="px-6 py-4 font-medium">Time</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800 text-center">
                {entriesLoading ? (
                  <tr>
                    <td
                      colSpan={5}
                      className="px-6 py-12 text-center text-zinc-500"
                    >
                      Loading data...
                    </td>
                  </tr>
                ) : entries.length === 0 ? (
                  <tr>
                    <td
                      colSpan={5}
                      className="px-6 py-12 text-center text-zinc-500"
                    >
                      No transactions today.
                    </td>
                  </tr>
                ) : (
                  entries.map((entry) => {
                    const status = entry.status;
                    return (
                      <tr
                        key={entry.id}
                        className="hover:bg-zinc-800/50 transition-colors"
                      >
                        <td className="py-4 font-medium text-white whitespace-nowrap">
                          <div className="flex items-center justify-center gap-2">
                            {status === "completed" && (
                              <>
                                <CheckCircle
                                  size={16}
                                  className="text-emerald-500 shrink-0"
                                />
                                <span>Completed</span>
                              </>
                            )}
                            {status === "pending" && (
                              <>
                                <XCircle
                                  size={16}
                                  className="text-yellow-500 shrink-0"
                                />
                                <span>Pending</span>
                              </>
                            )}
                            {status === "cancelled" && (
                              <>
                                <XCircle
                                  size={16}
                                  className="text-rose-500 shrink-0"
                                />
                                <span>Cancelled</span>
                              </>
                            )}
                          </div>
                        </td>
                        <td className="px-6 py-4 text-zinc-400">
                          {entry.user?.name ?? "—"}
                        </td>
                        <td className="px-6 py-4 text-yellow-500 font-semibold whitespace-nowrap">
                          -{entry.amount}
                        </td>
                        <td className="px-6 py-4 text-zinc-400 whitespace-nowrap">
                          {formatTime(entry.created_at)}
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MitraDashboard;
