// src/pages/mitra/MitraDashboard.tsx
import React, { useState, useCallback } from 'react';
import { ScanLine, Clock, CheckCircle, XCircle } from 'lucide-react';
import PinInput from '../../components/forms/PinInput';
import Button from '../../components/ui/Button';
import Badge from '../../components/ui/Badge';
import { useRecentEntries, useValidatePin } from '../../hooks/api/useMitraAPI';
import { useToastStore } from '../../store/toastStore';

const MitraDashboard: React.FC = () => {
  const [pin, setPin] = useState('');
  const [pinError, setPinError] = useState('');

  const { data: entries = [], isLoading: entriesLoading } = useRecentEntries();
  const validatePin = useValidatePin();
  const { addToast } = useToastStore();

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();
      setPinError('');
      const trimmedPin = pin.replace(/\s/g, '');
      if (trimmedPin.length !== 4 || !/^\d{4}$/.test(trimmedPin)) {
        setPinError('PIN harus terdiri dari 4 digit angka');
        return;
      }
      validatePin.mutate(
        { pin_code: trimmedPin },
        {
          onSuccess: () => {
            addToast('success', 'Validasi Sukses! Saldo member telah dipotong.');
            setPin('');
            setPinError('');
          },
          onError: (error) => {
            addToast('error', error.message || 'PIN tidak valid atau sudah kedaluwarsa');
            setPinError(error.message);
          },
        },
      );
    },
    [pin, validatePin, addToast],
  );

  const formatTime = (iso: string): string =>
    new Date(iso).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });

  const statusConfig: Record<string, { variant: 'success' | 'danger' | 'warning'; label: string }> = {
    completed: { variant: 'success', label: 'Berhasil' },
    failed: { variant: 'danger', label: 'Gagal' },
    expired: { variant: 'warning', label: 'Kedaluwarsa' },
  };

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 md:p-10">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-xl bg-yellow-500/10 mb-4">
            <ScanLine size={28} className="text-yellow-500" />
          </div>
          <h1 className="text-2xl md:text-3xl font-bold text-white">Validate Member Access</h1>
          <p className="text-zinc-400 mt-2">Enter the 4-digit PIN generated by the member's app</p>
        </div>
        <form onSubmit={handleSubmit} className="flex flex-col items-center gap-6">
          <PinInput value={pin} onChange={setPin} disabled={validatePin.isPending} error={pinError} />
          <Button type="submit" variant="primary" isLoading={validatePin.isPending} className="w-full max-w-xs py-4 text-lg font-extrabold tracking-wide">
            {validatePin.isPending ? 'Memvalidasi...' : 'VALIDASI PIN'}
          </Button>
        </form>
      </div>

      <div>
        <div className="flex items-center gap-2 mb-4">
          <Clock size={18} className="text-zinc-400" />
          <h2 className="text-lg font-semibold text-white">Recent Entries</h2>
        </div>
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-zinc-800 text-zinc-400 uppercase text-xs tracking-wider">
                  <th className="px-6 py-4 font-medium">Member</th>
                  <th className="px-6 py-4 font-medium">PIN</th>
                  <th className="px-6 py-4 font-medium text-right">Kredit</th>
                  <th className="px-6 py-4 font-medium text-center">Status</th>
                  <th className="px-6 py-4 font-medium text-right">Waktu</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800">
                {entriesLoading ? <tr><td colSpan={5} className="px-6 py-12 text-center text-zinc-500">Memuat data...</td></tr> : entries.map((entry) => {
                  const config = statusConfig[entry.status] ?? { variant: 'warning' as const, label: entry.status };
                  return (
                    <tr key={entry.id} className="hover:bg-zinc-800/50 transition-colors">
                      <td className="px-6 py-4 font-medium text-white whitespace-nowrap">
                        <div className="flex items-center gap-2">
                          {entry.status === 'completed' ? <CheckCircle size={16} className="text-emerald-500 shrink-0" /> : <XCircle size={16} className="text-rose-500 shrink-0" />}
                          {entry.user_name}
                        </div>
                      </td>
                      <td className="px-6 py-4 text-zinc-400 font-mono tracking-widest">{entry.pin_code}</td>
                      <td className="px-6 py-4 text-right text-yellow-500 font-semibold whitespace-nowrap">-{entry.credit_amount}</td>
                      <td className="px-6 py-4 text-center"><Badge variant={config.variant}>{config.label}</Badge></td>
                      <td className="px-6 py-4 text-right text-zinc-400 whitespace-nowrap">{formatTime(entry.created_at)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MitraDashboard;
