import React from 'react';
import Button from '../ui/Button';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'tos' | 'pp' | null;
}

const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose, type }) => {
  if (!isOpen || !type) return null;

  return (
    <div className="bg-black/80 backdrop-blur-sm fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="bg-zinc-900 w-full max-w-3xl rounded-3xl flex flex-col max-h-[85vh] border border-zinc-800 shadow-2xl">
        <h2 className="text-white font-bold border-b border-zinc-800 pb-4 m-6 mb-0 text-xl md:text-2xl">
          {type === 'tos' ? 'Terms of Service' : 'Privacy Policy'}
        </h2>
        
        <div className="overflow-y-auto p-6 text-sm text-zinc-300 space-y-6">
          {type === 'tos' ? (
            <>
              <p className="text-zinc-400"><strong>Effective Date: August 27, 2026</strong></p>
              <p>Welcome to RoamFit. These Terms of Service ("Agreement") constitute a legally binding agreement between you ("User" or "Member") and the operator of the RoamFit platform ("We" or "Us"). By registering, accessing, or using our services, you agree to be bound by all the terms and conditions below in accordance with applicable laws in the Republic of Indonesia.</p>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">1. Definitions</h3>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li><strong>RoamFit</strong> is a digital intermediary platform that facilitates pay-per-visit access to various fitness facilities.</li>
                  <li><strong>Gym Partner</strong> is a third party (independent fitness facility) that partners with RoamFit to accept User visits.</li>
                  <li><strong>Credit</strong> is the internal digital exchange value of RoamFit used to access Gym Partner facilities.</li>
                  <li><strong>Check-in PIN</strong> is a temporary unique code generated by the system to validate User access at the Gym Partner's location.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">2. Ecosystem Services & Limitation of Liability</h3>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li>RoamFit acts purely as a <strong>technology intermediary platform provider</strong>. We do not own, manage, or control the physical facilities, equipment, or staff at Gym Partner locations.</li>
                  <li>We are not responsible for any physical injuries, accidents, material losses, or lost belongings that occur while the User is at a Gym Partner's facility. The risk of using fitness equipment is entirely the User's responsibility.</li>
                  <li>Users must comply with all rules, operational hours, and dress codes unilaterally established by each Gym Partner.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">3. Credit System, Top-Up, and Non-Refundable Policy</h3>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li>RoamFit Credits can only be used within our platform ecosystem and have no cash value.</li>
                  <li><strong>Non-Refundable Policy:</strong> All successful Credit purchase transactions are final. Credits cannot be exchanged back for cash, transferred to a bank account, or refunded in any form.</li>
                  <li>If an account is closed, either at the User's request or due to a rule violation, all remaining Credits will be forfeited.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">4. Check-in Rules, PIN, and Balance Deduction</h3>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li>When a User presses the "Check-in" button, the system will hold (lock) Credits according to the Gym Partner's rate and generate a Check-in PIN.</li>
                  <li>The Check-in PIN has a time limit (Time-To-Live). If the User fails to present the PIN to the Gym Partner's receptionist before the time limit expires, the PIN will automatically expire and the Credit balance will <strong>not be deducted</strong> (fully returned to the User's wallet).</li>
                  <li>The Credit balance will only be permanently deducted when the Gym Partner successfully validates the PIN in their system.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">5. Account Suspension and Termination</h3>
                <p className="text-zinc-400 mb-2">We reserve the right, at our sole discretion, to suspend or delete a User account if there is suspected:</p>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li>Fraud, system manipulation, or transaction engineering.</li>
                  <li>Serious rule violations at Gym Partner facilities (based on Partner reports).</li>
                  <li>Actions that violate the positive laws of the Republic of Indonesia.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">6. Dispute Resolution</h3>
                <p className="text-zinc-400">Any disputes arising from this Agreement will be resolved amicably through consensus. If a consensus is not reached within 30 days, both parties agree to resolve it through the non-exclusive jurisdiction of the District Court where RoamFit's legal domicile is located.</p>
              </div>
            </>
          ) : (
            <>
              <p className="text-zinc-400"><strong>Effective Date: August 27, 2026</strong></p>
              <p>ROAM<span className="text-yellow-500">FIT</span> ("We" or "Us") highly respects and protects your data privacy. This Privacy Policy explains how We collect, use, store, and protect your personal information in accordance with <strong>Law Number 27 of 2022 concerning Personal Data Protection (UU PDP)</strong> of the Republic of Indonesia.</p>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">1. Data We Collect</h3>
                <p className="text-zinc-400 mb-2">When you use our application, We collect Specific and General Personal Data, including but not limited to:</p>
                <ul className="list-disc list-inside space-y-1 text-zinc-400">
                  <li><strong>Identity Data:</strong> Full name, email address, and password (stored in an encrypted/hashed format).</li>
                  <li><strong>Transaction Data:</strong> Credit mutation history, history of visited Gym facilities, and check-in/checkout times.</li>
                  <li><strong>Technical Data:</strong> Device information, IP address, and cookies (if accessed via a web browser) for session maintenance purposes.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">2. Purpose of Data Use</h3>
                <p className="text-zinc-400 mb-2">We use your Personal Data exclusively to:</p>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li>Process the creation and management of your RoamFit account.</li>
                  <li>Facilitate Credit deduction transactions and PIN issuance.</li>
                  <li>Provide customer support.</li>
                  <li>Conduct internal audits to prevent fraud (fraud detection).</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">3. Sharing Data with Third Parties (Gym Partners)</h3>
                <p className="text-zinc-400 mb-2">We will <strong>never sell</strong> your Personal Data to any third party. However, for the smooth operation of services, We will share a limited amount of your data with Gym Partners, namely:</p>
                <ul className="list-disc list-inside space-y-1 text-zinc-400">
                  <li>Your Profile Name.</li>
                  <li>PIN Validation Status and Visit Time.</li>
                </ul>
                <p className="text-zinc-400 mt-2">This is absolutely necessary so that the Gym Partner's receptionist can verify your identity when you arrive at the location.</p>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">4. Data Security and Retention</h3>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li>We protect your Personal Data using industry encryption standards for data exchange (HTTPS/SSL) and authentication tokenization mechanisms (such as Bearer Tokens).</li>
                  <li>Password data is encrypted using a one-way hashing algorithm; our staff does not have access to view your original password.</li>
                  <li>We will retain your Personal Data for as long as your account is active, or as long as necessary to fulfill legal, tax, or dispute resolution obligations in Indonesia.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">5. Your Rights (Data Subject)</h3>
                <p className="text-zinc-400 mb-2">In accordance with the PDP Law, you have full rights to:</p>
                <ul className="list-decimal list-inside space-y-1 text-zinc-400">
                  <li>Request access to your Personal Data that We store.</li>
                  <li>Request corrections (updates) if there is inaccurate data (via the "Edit Profile" menu).</li>
                  <li>Request permanent deletion of your Personal Data from our system (Right to be Erasure), with the note that any remaining Credit balance will be forfeited.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-yellow-500 font-bold mb-2 text-base">6. Policy Changes & Contact</h3>
                <p className="text-zinc-400 mb-2">We reserve the right to update this Privacy Policy from time to time. If there are material changes, We will notify you via email or application notification.</p>
                <p className="text-zinc-400">For questions, complaints, or the exercise of Data Subject Rights, you can contact our Data Protection Officer (DPO) / Admin Team via email: <strong>privacy@roamfit.com</strong> or the "Contact Us" feature in the application.</p>
              </div>
            </>
          )}
        </div>

        <div className="p-6 pt-0 mt-auto border-t border-zinc-800 mt-4 pt-6">
          <Button variant="primary" className="w-full py-4 text-sm font-bold uppercase tracking-widest" onClick={onClose}>
            Understand & Close
          </Button>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;
